// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkfn2aKKVa9M6he1kr9s4LZ4G89FSEzzI',
    appId: '1:914919015452:web:f5d60a130c4c2a438ccbd9',
    messagingSenderId: '914919015452',
    projectId: 'mind-aware-b89c3',
    authDomain: 'mind-aware-b89c3.firebaseapp.com',
    storageBucket: 'mind-aware-b89c3.firebasestorage.app',
    measurementId: 'G-DTSJ4FR14X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBhVXcJYvdKaWSLgFQjuLywRfMIA3Dh6Q',
    appId: '1:914919015452:android:e9607ca0239bb9b68ccbd9',
    messagingSenderId: '914919015452',
    projectId: 'mind-aware-b89c3',
    storageBucket: 'mind-aware-b89c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2bwAemQZBIq8NYe5Vq2eVO9IE_S2DMg',
    appId: '1:914919015452:ios:d3611e16ba5789e48ccbd9',
    messagingSenderId: '914919015452',
    projectId: 'mind-aware-b89c3',
    storageBucket: 'mind-aware-b89c3.firebasestorage.app',
    iosBundleId: 'com.example.mindAwareApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2bwAemQZBIq8NYe5Vq2eVO9IE_S2DMg',
    appId: '1:914919015452:ios:d3611e16ba5789e48ccbd9',
    messagingSenderId: '914919015452',
    projectId: 'mind-aware-b89c3',
    storageBucket: 'mind-aware-b89c3.firebasestorage.app',
    iosBundleId: 'com.example.mindAwareApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkfn2aKKVa9M6he1kr9s4LZ4G89FSEzzI',
    appId: '1:914919015452:web:41f16f5d116b90da8ccbd9',
    messagingSenderId: '914919015452',
    projectId: 'mind-aware-b89c3',
    authDomain: 'mind-aware-b89c3.firebaseapp.com',
    storageBucket: 'mind-aware-b89c3.firebasestorage.app',
    measurementId: 'G-GJP9GQHBRQ',
  );

}